"""
Paper III, Task 3: Extended-source eta for DGSAT-I (Plummer profile).

Approach: in the absence of an explicit closed-form operator, we evaluate
eta-1 = (2 beta/3)/sqrt(y(1+y))   with y = g_N(r)/a0
using the EXTENDED g_N from the Plummer enclosed mass, instead of the
point-source g_N = GM/r^2 of Paper I.  This is the standard Paper-II
caveat ("local-g_N substitution").  The non-local operator analysis of
Task 1 shows the Green function decays as r^{-1/2} (slower than 1/r),
so the true extended eta will sit between the point-source value and
the local-g_N value -- the latter is the more conservative reduction.
"""
import numpy as np

G = 6.674e-11
a0 = 1.2e-10
beta = 0.0075
Msun = 1.989e30
kpc  = 3.086e19

# DGSAT-I (corrected values, see Paper I errata)
M     = 3.0e8 * Msun
r_eff = 4.7 * kpc                     # photometric half-light = Plummer r_p
r_p   = r_eff

# Point-source eta at r_eff
g_N_pt = G*M/r_eff**2
y_pt   = g_N_pt/a0
eta_pt = 1.0 + (2*beta/3)/np.sqrt(y_pt*(1+y_pt))

# Plummer enclosed mass and g_N
def Menc_plummer(r, M, rp):
    return M * r**3 / (r**2 + rp**2)**1.5

g_N_ext = G*Menc_plummer(r_eff, M, r_p)/r_eff**2
y_ext   = g_N_ext/a0
eta_ext = 1.0 + (2*beta/3)/np.sqrt(y_ext*(1+y_ext))

# r_MOND
r_MOND = np.sqrt(G*M/a0)
eps    = r_eff/r_MOND

with open('dgsat_extended_result.txt','w', encoding='utf-8') as f:
    f.write("DGSAT-I extended-source slip prediction (Paper III)\n")
    f.write("="*60 + "\n")
    f.write(f"M = {M/Msun:.3e} Msun, r_eff = r_p = {r_eff/kpc:.2f} kpc\n")
    f.write(f"r_MOND = {r_MOND/kpc:.3f} kpc, epsilon = r_eff/r_MOND = {eps:.2f}\n\n")
    f.write("Point-source (Paper I):\n")
    f.write(f"  g_N(r_eff) = {g_N_pt:.3e} m/s^2,   y = {y_pt:.4f}\n")
    f.write(f"  eta - 1    = {(eta_pt-1)*100:.2f} %\n\n")
    f.write("Extended (Plummer enclosed mass at r_eff):\n")
    f.write(f"  g_N(r_eff) = {g_N_ext:.3e} m/s^2,  y = {y_ext:.4f}\n")
    f.write(f"  eta - 1    = {(eta_ext-1)*100:.2f} %\n\n")
    f.write(f"Ratio (extended / point) = {(eta_ext-1)/(eta_pt-1):.3f}\n\n")
    f.write("CAVEAT (Paper III, sec. II): the operator-level analysis of\n")
    f.write("Task 1 shows the slip field is generated by a non-local\n")
    f.write("operator whose Green function decays as r^{-1/2}.  The local-g_N\n")
    f.write("substitution above is therefore an UPPER bound on the\n")
    f.write("conservative reduction; the full non-local convolution would\n")
    f.write("yield a value between the point-source eta-1 and the local-g_N\n")
    f.write("eta-1 reported here.\n")
print(open('dgsat_extended_result.txt').read())
